[package]
name = "tinydb"
version = "0.1.0"
edition = "2018"

[dependencies]
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"

[dev-dependencies]
tempfile = "3.2"
rand = "0.8.5"
